# Generated by Django 3.1.4 on 2020-12-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
